### ISSUE TITLE
POST status/hosts/{hostname}/results not work

### ISSUE THREAD

**Issue by ddurieux** [surveil/surveil-meta#110]
Try with this command: 

curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"address":"localhost"}' http://10.0.20.11:5311/v2/status/hosts/localhost/results

it return:

{"debuginfo": null, "faultcode": "Client", "faultstring": "Invalid input for field/attribute return_code. Value: 'None'. Mandatory field missing."}

In this class, no fields are mandatory, so I think there is a problem

**Comment by aviau** [comment]
`return_code` is mandatory in the [CheckResult datamodel](https://github.com/stackforge/surveil/blob/master/surveil/api/datamodel/checkresult.py).

I have added one example in changeset [I4ee334e8ff922411a90b60578e016a43378290e9.](https://review.openstack.org/#/c/205586/)

Make sure that `passive_checks_enabled` is set to `'1'`

For example, submit check results with the following command:

```
reazem@cranberry:~/git/surveil$ surveil status-submit-check-result --host_name=passive_check_host --return_code=0 --output='Hello!'
reazem@cranberry:~/git/surveil$ surveil status-host-list
+--------------------------+---------------+---------+------------+-----------------------------------+
| host_name                | address       | state   | last_check | plugin_output                     |
+--------------------------+---------------+---------+------------+-----------------------------------+
| localhost                | localhost     | PENDING | 0          | ...                               |
| ws-arbiter               | localhost     | PENDING | 0          | ...                               |
| test_keystone            | 127.0.0.1     | PENDING | 0          | ...                               |
| openstackceilometer-host | 127.0.0.1     | UP      | 1437753476 | OK - 127.0.0.1: rta 0.042ms, l... |
| srv-apache-01            | srv-apache-01 | DOWN    | 1437753471 | check_icmp: Failed to resolve ... |
| myparentisdown           | dfgsdgsdgf    | PENDING | 0          | ...                               |
| google.com               | google.com    | PENDING | 0          | ...                               |
| srv-monitoring-01        | 127.0.0.1     | PENDING | 0          | ...                               |
| myserviceisdown          | localhost     | PENDING | 0          | ...                               |
| passive_check_host       | 127.0.0.1     | UP      | 1437753417 | Hello!...                         |
| sw-iwebcore-01           | 127.0.0.1     | PENDING | 0          | ...                               |
| srv-ldap-01              | 127.0.0.1     | PENDING | 0          | ...                               |
+--------------------------+---------------+---------+------------+-----------------------------------+
```

**Comment by ddurieux** [comment]
With your command I have : 

```
('Connection aborted.', error(61, 'Connection refused')) (HTTP 500)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/surveilclient/shell.py", line 173, in main
    SurveilShell().main(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/surveilclient/shell.py", line 161, in main
    return cfg.func(client, cfg)
  File "/usr/local/lib/python2.7/site-packages/surveilclient/v2_0/shell.py", line 435, in do_status_submit_check_result
    return_code=int(args.return_code),
  File "/usr/local/lib/python2.7/site-packages/surveilclient/v2_0/status/hosts.py", line 44, in submit_check_result
    body=kwargs
  File "/usr/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 115, in json_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 127, in request
    resp, body = self._http_request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 98, in _http_request
    response=resp, body=body_str, method=method, url=url)
HttpError: ('Connection aborted.', error(61, 'Connection refused')) (HTTP 500)
```
