### ISSUE TITLE
Bug with surveil API

### ISSUE THREAD

**Issue by titilambert** [surveil/surveil-meta#81]

**Comment by titilambert** [comment]
`surveil status-metrics-show --host_name ws-arbiter --metric_name pl`

```
400: {"error":"error parsing query: only ORDER BY ASC supported at this time"} (HTTP 400)
Traceback (most recent call last):
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/shell.py", line 173, in main
    SurveilShell().main(sys.argv[1:])
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/shell.py", line 161, in main
    return cfg.func(client, cfg)
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/v2_0/shell.py", line 417, in do_status_metrics_show
    metric = sc.status.hosts.metrics.get(**arg)
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/v2_0/status/metrics/metrics.py", line 47, in get
    resp, body = self.http_client.json_request(url, 'GET')
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 115, in json_request
    resp, body = self.request(url, method, **kwargs)
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 127, in request
    resp, body = self._http_request(url, method, **kwargs)
  File "/tmp/env/local/lib/python2.7/site-packages/surveilclient/common/http.py", line 98, in _http_request
    response=resp, body=body_str, method=method, url=url)
HttpError: 400: {"error":"error parsing query: only ORDER BY ASC supported at this time"} (HTTP 400)
```
